#!/usr/bin/env python3
"""SMALLEST proof-of-loop orchestrator for the Paradigm-Shift Finder.

Goal: prove the core loop works WITHOUT hallucination before scaling to the
7-epoch / 200-candidate run_013 configuration. Scope is deliberately tiny:
1 epoch, 3 candidates, 1 real Opus subprocess merge per candidate.

The loop proves four things, each with a hard, mechanical check:

  1. Opus subprocess merge -> REAL candidate (not mock concat).
     Each candidate is generated by `claude -p --model opus`. The full JSON
     envelope (result text + session_id + token usage + cost) is captured
     verbatim. A session_id and token usage cannot be fabricated in-context,
     so a [REPORT] block is proof the call really happened.

  2. [REPORT] injection shows raw ground truth.
     Every Opus envelope is written verbatim into logs/report_log.md under a
     [REPORT] tag. Downstream steps read the parsed candidate, but the raw
     envelope stays as the immutable ground truth.

  3. The 4-gate filter runs DETERMINISTICALLY.
     The merge is the stochastic generation step; the 4 gates are a pure
     function of the frozen candidate record. We run the gates twice over the
     frozen records and assert the two verdict hashes are byte-identical.

  4. No hallucination: the LLM summary matches the [REPORT] raw log.
     One final Opus call reads ONLY the raw log + gate results and re-states
     the key numbers. A pure-Python checker diffs those numbers field-by-field
     against the ground truth. Any divergence => HALLUCINATION_DETECTED, and
     the run exits non-zero.

The four gates are inherited verbatim from run_013's harness_rules.json, so
this is the same filter at the smallest possible scale.

Usage:
    python3 paradigm_shift/smallest_loop.py            # full run (real Opus x4)
    python3 paradigm_shift/smallest_loop.py --no-opus  # gates-only dry run
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

THIS_DIR = Path(__file__).parent
sys.path.insert(0, str(THIS_DIR))

import multi_parameter_scorer as scorer  # noqa: E402  (deterministic Gate 1 composite)

RUN_DIR = THIS_DIR / "runs" / "run_014_smallest"
LOGS_DIR = RUN_DIR / "logs"
RULES_PATH = RUN_DIR / "smallest_rules.json"
INPUTS_PATH = RUN_DIR / "candidates_input.json"


# --------------------------------------------------------------------------- #
# Config loading
# --------------------------------------------------------------------------- #
def load_config() -> tuple[dict, dict, dict]:
    """Return (rules, gate_params, inputs).

    gate_params are read from the inherited run_013 spec so the gates here are
    literally the run_013 gates.
    """
    rules = json.loads(RULES_PATH.read_text())
    inherit_path = THIS_DIR.parent / rules["inherit_gates_from"]
    spec = json.loads(inherit_path.read_text())
    gate_params = {
        "composite_threshold": spec["composite_threshold"],
        "quarantined_atoms": spec["quarantined_atoms"],
        "min_web_search_per_candidate": spec["min_web_search_per_candidate"],
        "belinda_strict": spec["belinda_strict"],
        "_inherited_from": str(inherit_path),
    }
    inputs = json.loads(INPUTS_PATH.read_text())
    return rules, gate_params, inputs


# --------------------------------------------------------------------------- #
# Step 1+2: real Opus subprocess merge -> [REPORT] ground truth
# --------------------------------------------------------------------------- #
MERGE_PROMPT = """You are merging two research "atoms" into ONE candidate paradigm-shift research niche in AI / LLMs.

ATOM A (id {a_id}, source {a_src}): "{a_text}"
ATOM B (id {b_id}, source {b_src}): "{b_text}"

Combine the mechanism in ATOM A with the mechanism/principle in ATOM B into a single, concrete, testable research direction.

Output ONLY a fenced ```json block (no prose before or after) with EXACTLY these fields:
{{
  "joint_topic": "<=12 word title of the merged niche",
  "thesis": "1-2 sentence concrete research thesis",
  "mechanism": "1-2 sentences describing the causal mechanism; MUST use concrete causal verbs such as induces, produces, causes, transforms, regulates, activates, inhibits, routes",
  "operator": "a short relation label such as INDUCES or TRANSFORMS; do NOT use ANALOGY_TRANSFERS_TO_OPEN",
  "primary_quote": "a quote of at least 30 characters copied EXACTLY (verbatim, character-for-character) from ATOM A's text or ATOM B's text; do not paraphrase or invent",
  "verification_plan": [{{"source": "<name>", "query": "<search query>"}}]
}}

Rules:
- primary_quote MUST be an exact substring of one atom's text. Copy it; do not invent.
- verification_plan MUST list at least 5 entries with 5 DISTINCT source names.
- Output nothing except the json block."""


_SUBPROC_CWD: str | None = None


def _subproc_cwd(cfg: dict) -> str | None:
    """A throwaway non-git temp dir for the Opus subprocess.

    Running outside any git repo makes the host's git Stop-hook bail early
    (`git rev-parse --git-dir` fails) instead of hijacking the merge output
    with a "commit your changes" message. Auth is environment-based and so is
    unaffected by cwd.
    """
    if not cfg.get("run_in_nongit_tempdir"):
        return None
    global _SUBPROC_CWD
    if _SUBPROC_CWD is None:
        _SUBPROC_CWD = tempfile.mkdtemp(prefix="autoresearch_opus_")
    return _SUBPROC_CWD


def run_opus(prompt: str, rules: dict) -> dict:
    """Invoke a real Opus subprocess and return the full JSON envelope.

    Raises on non-zero exit or unparseable envelope so failures are loud. The
    call is isolated to pure text generation: tools disallowed, run in a
    non-git temp dir (see _subproc_cwd).
    """
    cfg = rules["opus_subprocess"]
    cmd = [cfg["binary"], *cfg["args"]]
    if cfg.get("disallowed_tools"):
        cmd += ["--disallowedTools", *cfg["disallowed_tools"]]
    proc = subprocess.run(
        cmd,
        input=prompt,
        capture_output=True,
        text=True,
        timeout=cfg["timeout_seconds"],
        cwd=_subproc_cwd(cfg),
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"opus subprocess exit {proc.returncode}: {proc.stderr[:500]}"
        )
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"opus envelope not JSON: {exc}; raw={proc.stdout[:500]}")


def extract_json_block(text: str) -> dict | None:
    """Extract the last fenced ```json block, falling back to a balanced {...}."""
    fences = re.findall(r"```(?:json)?\s*(\{.*?\})\s*```", text, flags=re.DOTALL)
    for block in reversed(fences):
        try:
            return json.loads(block)
        except json.JSONDecodeError:
            continue
    # fallback: first balanced top-level object
    start = text.find("{")
    while start != -1:
        depth = 0
        for i in range(start, len(text)):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    try:
                        return json.loads(text[start : i + 1])
                    except json.JSONDecodeError:
                        break
        start = text.find("{", start + 1)
    return None


def opus_merge(cand_input: dict, rules: dict) -> dict:
    """Step 1+2: generate a candidate via a real Opus subprocess.

    Returns a merge record carrying the full envelope (ground truth) and the
    parsed candidate fields.
    """
    a, b = cand_input["atom_a"], cand_input["atom_b"]
    prompt = MERGE_PROMPT.format(
        a_id=a["atom_id"], a_src=a["source_type"], a_text=a["text"],
        b_id=b["atom_id"], b_src=b["source_type"], b_text=b["text"],
    )
    envelope = run_opus(prompt, rules)
    result_text = envelope.get("result", "")
    parsed = extract_json_block(result_text)
    return {
        "cand_id": cand_input["cand_id"],
        "parse_ok": parsed is not None,
        "parsed_candidate": parsed,
        "envelope": envelope,
        "prompt": prompt,
        "merged_at": datetime.now(timezone.utc).isoformat(),
    }


def append_report_block(cand_id: str, envelope: dict) -> None:
    """Step 2: inject the raw envelope into the [REPORT] log, verbatim."""
    usage = envelope.get("usage", {})
    block = [
        f"\n## [REPORT] {cand_id}",
        f"- session_id: `{envelope.get('session_id')}`",
        f"- duration_ms: {envelope.get('duration_ms')}  "
        f"total_cost_usd: {envelope.get('total_cost_usd')}  "
        f"num_turns: {envelope.get('num_turns')}",
        f"- usage: input={usage.get('input_tokens')} "
        f"output={usage.get('output_tokens')} "
        f"cache_read={usage.get('cache_read_input_tokens')}",
        "- raw envelope (verbatim ground truth):",
        "```json",
        json.dumps(envelope, indent=2, sort_keys=True),
        "```",
    ]
    with (LOGS_DIR / "report_log.md").open("a") as f:
        f.write("\n".join(block) + "\n")


# --------------------------------------------------------------------------- #
# Freeze: the boundary between stochastic generation and deterministic gating
# --------------------------------------------------------------------------- #
def freeze_record(cand_input: dict, parsed: dict | None) -> dict:
    """Assemble the immutable record the gates operate on.

    Everything stochastic (the Opus output) is captured here once; gates are a
    pure function of this frozen record thereafter.
    """
    parsed = parsed or {}
    return {
        "cand_id": cand_input["cand_id"],
        "atom_a": cand_input["atom_a"],
        "atom_b": cand_input["atom_b"],
        "smoke_io": cand_input["smoke_io"],
        "joint_topic": parsed.get("joint_topic", ""),
        "mechanism": parsed.get("mechanism", ""),
        "operator": parsed.get("operator", ""),
        "primary_quote": parsed.get("primary_quote", ""),
        "verification_plan": parsed.get("verification_plan", []),
    }


def _norm_ws(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "")).strip()


def verification_sources(vplan: Any) -> list[str]:
    """Distinct, normalized verification-source names from a merge's plan.

    Tolerant of both the structured form [{"source","query"}, ...] and a bare
    list of citation strings — either way we count distinct proposed
    verification targets.
    """
    sources: set[str] = set()
    if isinstance(vplan, list):
        for v in vplan:
            if isinstance(v, dict):
                raw = v.get("source") or v.get("name") or ""
            else:
                raw = str(v)
            s = _norm_ws(raw).lower()
            if s:
                sources.add(s)
    return sorted(sources)


# --------------------------------------------------------------------------- #
# Step 3: the deterministic 4-gate filter (pure function of a frozen record)
# --------------------------------------------------------------------------- #
def run_four_gates(rec: dict, gp: dict, weights: dict) -> dict:
    """Apply the four run_013 gates to a frozen candidate record.

    DETERMINISTIC: identical (rec, gp, weights) => identical verdict. No clocks,
    no I/O, no randomness. The returned dict carries no timestamps so it hashes
    stably.
    """
    # ---- Gate 1: composite >= threshold (deterministic scorer) ----
    a, b = rec["atom_a"], rec["atom_b"]
    io = rec["smoke_io"]
    cand = scorer.Candidate(
        cand_id=rec["cand_id"],
        atom_a=scorer.Atom(a["atom_id"], a["source_id"], a["source_type"],
                           a["speaker_or_author"], a["text"], a["atom_type"],
                           a.get("domain_tags", [])),
        atom_b=scorer.Atom(b["atom_id"], b["source_id"], b["source_type"],
                           b["speaker_or_author"], b["text"], b["atom_type"],
                           b.get("domain_tags", [])),
        joint_topic=rec["joint_topic"],
        arxiv_hit_count_24m=io["arxiv_hit_count_24m"],
        recent_paper_count=io["recent_paper_count"],
        saturation_cluster_distance=io["saturation_cluster_distance"],
        arxiv_citations_supporting=io["arxiv_citations_supporting"],
        belinda_3q_passes=io["belinda_3q_passes"],
    )
    score = scorer.score_candidate(cand, weights)
    composite = score["composite_score"]
    gate1 = composite >= gp["composite_threshold"]

    # ---- Gate 2: quarantine ----
    quarantine = set(gp["quarantined_atoms"])
    ids = {a["atom_id"], b["atom_id"]}
    hits = sorted(ids & quarantine)
    gate2 = len(hits) == 0

    # ---- Gate 3: structural cross-LLM/verification slots ----
    distinct_sources = verification_sources(rec["verification_plan"])
    gate3 = len(distinct_sources) >= gp["min_web_search_per_candidate"]

    # ---- Gate 4: Belinda strict (mechanism verb + operator + grounded quote) ----
    bs = gp["belinda_strict"]
    mech = _norm_ws(rec["mechanism"]).lower()
    verbs_hit = sorted(v for v in bs["mechanism_vocab"]
                       if re.search(r"\b" + re.escape(v) + r"\b", mech))
    operator_ok = rec["operator"] not in set(bs["rejected_operators"])
    quote = _norm_ws(rec["primary_quote"])
    long_enough = len(quote) >= bs["min_verbatim_chars"]
    atom_text = _norm_ws(a["text"] + " " + b["text"])
    grounded = bool(quote) and quote in atom_text  # anti-hallucination grounding
    gate4 = bool(verbs_hit) and operator_ok and long_enough and grounded

    survived = gate1 and gate2 and gate3 and gate4
    gates_failed = [name for name, ok in
                    (("gate_1_threshold", gate1), ("gate_2_quarantine", gate2),
                     ("gate_3_cross_llm", gate3), ("gate_4_belinda", gate4))
                    if not ok]
    return {
        "cand_id": rec["cand_id"],
        "joint_topic": rec["joint_topic"],
        "operator": rec["operator"],
        "mechanism": rec["mechanism"],
        "primary_quote": rec["primary_quote"],
        "composite": composite,
        "gate_1_threshold": {"pass": gate1, "composite": composite,
                             "threshold": gp["composite_threshold"]},
        "gate_2_quarantine": {"pass": gate2, "quarantine_hits": hits},
        "gate_3_cross_llm": {"pass": gate3, "distinct_sources": distinct_sources,
                             "required": gp["min_web_search_per_candidate"]},
        "gate_4_belinda": {"pass": gate4, "mechanism_verbs": verbs_hit,
                           "operator": rec["operator"], "operator_ok": operator_ok,
                           "quote_chars": len(quote), "quote_grounded": grounded},
        "survived": survived,
        "gates_failed": gates_failed,
        "first_drop_gate": _first_drop(gate1, gate2, gate3, gate4),
    }


def _first_drop(g1: bool, g2: bool, g3: bool, g4: bool) -> str | None:
    for name, ok in (("gate_1_threshold", g1), ("gate_2_quarantine", g2),
                     ("gate_3_cross_llm", g3), ("gate_4_belinda", g4)):
        if not ok:
            return name
    return None


def gate_all(frozen_records: list[dict], gp: dict, weights: dict) -> list[dict]:
    return [run_four_gates(r, gp, weights) for r in frozen_records]


def verdicts_hash(verdicts: list[dict]) -> str:
    """Stable hash of the pass/fail decisions only (the determinism contract)."""
    skeleton = [
        {
            "cand_id": v["cand_id"],
            "composite": v["composite"],
            "g1": v["gate_1_threshold"]["pass"],
            "g2": v["gate_2_quarantine"]["pass"],
            "g3": v["gate_3_cross_llm"]["pass"],
            "g4": v["gate_4_belinda"]["pass"],
            "survived": v["survived"],
        }
        for v in verdicts
    ]
    blob = json.dumps(skeleton, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(blob.encode()).hexdigest()


# --------------------------------------------------------------------------- #
# niche_find_check verdict
# --------------------------------------------------------------------------- #
def build_verdict(verdicts: list[dict]) -> dict:
    survivors = [v for v in verdicts if v["survived"]]
    gates = ["gate_1_threshold", "gate_2_quarantine",
             "gate_3_cross_llm", "gate_4_belinda"]
    # first-fail attribution (matches the spec's niche_find_check drop_counts)
    drop_counts = {g: 0 for g in gates}
    # any-fail attribution: every gate that dropped a candidate gets credit,
    # so a gate is visibly "firing" even when an earlier gate also failed.
    gate_fired_counts = {g: 0 for g in gates}
    for v in verdicts:
        if v["first_drop_gate"]:
            drop_counts[v["first_drop_gate"]] += 1
        for g in v["gates_failed"]:
            gate_fired_counts[g] += 1
    return {
        "verdict": "NICHE_FOUND" if survivors else "NICHE_NOT_FOUND",
        "survivors": [
            {"cand_id": s["cand_id"], "composite": s["composite"],
             "joint_topic": s["joint_topic"], "operator": s["operator"],
             "mechanism": s["mechanism"], "primary_quote": s["primary_quote"]}
            for s in survivors
        ],
        "drop_counts": drop_counts,
        "gate_fired_counts": gate_fired_counts,
        "per_candidate_gates_failed": {
            v["cand_id"]: v["gates_failed"] for v in verdicts},
        "candidates_scanned": len(verdicts),
        "notes": ("At least one candidate passed all four gates. "
                  if survivors else
                  "No candidate passed all four gates. ") +
                 "drop_counts = first gate each candidate failed; "
                 "gate_fired_counts = every gate that dropped a candidate "
                 "(so Gate 2 quarantine is credited even when Gate 1 also failed).",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


# --------------------------------------------------------------------------- #
# Step 4: anti-hallucination check (LLM summary vs [REPORT] ground truth)
# --------------------------------------------------------------------------- #
SUMMARY_PROMPT = """You are writing a strictly factual summary of an automated run.
Below is the RAW REPORT LOG (ground truth) and the GATE RESULTS (ground truth).

=== RAW REPORT LOG ===
{report_log}

=== GATE RESULTS (JSON, ground truth) ===
{gate_results}

Write 3-6 plain-English sentences summarizing what happened. State ONLY facts
present above; do not infer, round, or embellish any number.

Then output a fenced ```json block with EXACTLY these fields, copying the
numbers from the GATE RESULTS above:
{{
  "n_candidates": <int>,
  "n_survivors": <int>,
  "verdict": "<NICHE_FOUND or NICHE_NOT_FOUND>",
  "per_candidate": [{{"cand_id": "<id>", "composite": <number>, "survived": <true|false>}}]
}}"""


def ground_truth_claims(verdicts: list[dict], verdict_doc: dict) -> dict:
    return {
        "n_candidates": len(verdicts),
        "n_survivors": len(verdict_doc["survivors"]),
        "verdict": verdict_doc["verdict"],
        "per_candidate": [
            {"cand_id": v["cand_id"], "composite": round(v["composite"], 4),
             "survived": v["survived"]}
            for v in verdicts
        ],
    }


def check_hallucination(truth: dict, claimed: dict | None) -> dict:
    """Diff LLM-stated numbers against ground truth. Any divergence => detected."""
    mismatches: list[str] = []
    if claimed is None:
        return {"hallucination_detected": True, "no_hallucination": False,
                "mismatches": ["LLM summary produced no parseable claim block"],
                "truth": truth, "claimed": None}

    for key in ("n_candidates", "n_survivors", "verdict"):
        if claimed.get(key) != truth[key]:
            mismatches.append(
                f"{key}: claimed {claimed.get(key)!r} != truth {truth[key]!r}")

    truth_by_id = {c["cand_id"]: c for c in truth["per_candidate"]}
    claimed_by_id = {c.get("cand_id"): c for c in claimed.get("per_candidate", [])}

    for cid in claimed_by_id:
        if cid not in truth_by_id:
            mismatches.append(f"fabricated cand_id not in ground truth: {cid!r}")

    for cid, t in truth_by_id.items():
        c = claimed_by_id.get(cid)
        if c is None:
            mismatches.append(f"missing cand_id in summary: {cid!r}")
            continue
        try:
            if abs(float(c.get("composite")) - float(t["composite"])) > 1e-4:
                mismatches.append(
                    f"{cid} composite: claimed {c.get('composite')} "
                    f"!= truth {t['composite']}")
        except (TypeError, ValueError):
            mismatches.append(f"{cid} composite not a number: {c.get('composite')!r}")
        if bool(c.get("survived")) != bool(t["survived"]):
            mismatches.append(
                f"{cid} survived: claimed {c.get('survived')} "
                f"!= truth {t['survived']}")

    detected = len(mismatches) > 0
    return {"hallucination_detected": detected, "no_hallucination": not detected,
            "mismatches": mismatches, "truth": truth, "claimed": claimed}


# --------------------------------------------------------------------------- #
# Orchestration
# --------------------------------------------------------------------------- #
def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="SMALLEST proof-of-loop run")
    ap.add_argument("--no-opus", action="store_true",
                    help="skip Opus subprocess calls (gates-only dry run)")
    args = ap.parse_args(argv)

    rules, gp, inputs = load_config()
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    weights = scorer.load_weights()

    # fresh report log
    (LOGS_DIR / "report_log.md").write_text(
        f"# [REPORT] ground-truth log — run_014_smallest\n"
        f"# generated {datetime.now(timezone.utc).isoformat()}\n"
        f"# Each block is the verbatim JSON envelope from a real Opus subprocess.\n")

    print("=" * 70)
    print("SMALLEST proof-of-loop run — 1 epoch, 3 candidates, 1 Opus call each")
    print("=" * 70)

    # ---- Step 1+2: merges + [REPORT] injection ----
    frozen_records: list[dict] = []
    for cand_input in inputs["candidates"]:
        cid = cand_input["cand_id"]
        if args.no_opus:
            print(f"[merge] {cid}: --no-opus, skipping (no frozen record)")
            continue
        print(f"[merge] {cid}: invoking real Opus subprocess ...", flush=True)
        merge = opus_merge(cand_input, rules)
        append_report_block(cid, merge["envelope"])
        (LOGS_DIR / f"merge_{cid}.json").write_text(json.dumps(merge, indent=2))
        env = merge["envelope"]
        print(f"  -> session {env.get('session_id')}  "
              f"parse_ok={merge['parse_ok']}  "
              f"cost=${env.get('total_cost_usd')}  "
              f"out_tokens={env.get('usage', {}).get('output_tokens')}")
        frozen_records.append(freeze_record(cand_input, merge["parsed_candidate"]))

    if args.no_opus:
        print("\n--no-opus: nothing more to do (the loop needs real merges).")
        return 0

    (LOGS_DIR / "frozen_records.json").write_text(json.dumps(frozen_records, indent=2))

    # ---- Step 3: deterministic 4-gate + determinism proof ----
    print("\n[gates] applying deterministic 4-gate filter ...")
    verdicts_a = gate_all(copy.deepcopy(frozen_records), gp, weights)
    verdicts_b = gate_all(copy.deepcopy(frozen_records), gp, weights)
    hash_a, hash_b = verdicts_hash(verdicts_a), verdicts_hash(verdicts_b)
    determinism_ok = hash_a == hash_b
    det_doc = {"determinism_ok": determinism_ok, "hash_run_1": hash_a,
               "hash_run_2": hash_b, "runs": 2,
               "note": "Gates run twice over identical frozen records; "
                       "verdict hashes must be byte-identical."}
    (LOGS_DIR / "determinism_check.json").write_text(json.dumps(det_doc, indent=2))
    (LOGS_DIR / "gate_results.json").write_text(json.dumps(verdicts_a, indent=2))
    for v in verdicts_a:
        flags = "".join("1" if v[f"gate_{i}_{n}"]["pass"] else "0"
                        for i, n in ((1, "threshold"), (2, "quarantine"),
                                     (3, "cross_llm"), (4, "belinda")))
        print(f"  {v['cand_id']}: composite={v['composite']:.4f} gates[{flags}] "
              f"survived={v['survived']} first_drop={v['first_drop_gate']}")
    print(f"  determinism: {'OK (hashes match)' if determinism_ok else 'BROKEN'}  "
          f"{hash_a[:16]}...")

    # ---- niche verdict ----
    verdict_doc = build_verdict(verdicts_a)
    (RUN_DIR / "niche_find_check.json").write_text(json.dumps(verdict_doc, indent=2))
    print(f"\n[verdict] {verdict_doc['verdict']} "
          f"({len(verdict_doc['survivors'])} survivor(s))")
    print(f"  first-fail drop_counts: {verdict_doc['drop_counts']}")
    print(f"  any-fail gate_fired_counts: {verdict_doc['gate_fired_counts']}")

    # ---- Step 4: anti-hallucination check ----
    print("\n[anti-hallucination] asking Opus to summarize ONLY the raw log ...")
    truth = ground_truth_claims(verdicts_a, verdict_doc)
    summary_prompt = SUMMARY_PROMPT.format(
        report_log=(LOGS_DIR / "report_log.md").read_text(),
        gate_results=json.dumps(verdicts_a, indent=2),
    )
    summary_env = run_opus(summary_prompt, rules)
    summary_text = summary_env.get("result", "")
    (LOGS_DIR / "summary_llm.md").write_text(
        f"# LLM summary (session {summary_env.get('session_id')})\n\n{summary_text}\n")
    append_report_block("SUMMARY_CALL", summary_env)
    claimed = extract_json_block(summary_text)
    hall = check_hallucination(truth, claimed)
    (LOGS_DIR / "hallucination_check.json").write_text(json.dumps(hall, indent=2))
    if hall["no_hallucination"]:
        print("  -> NO HALLUCINATION: LLM summary numbers match ground truth.")
    else:
        print("  -> HALLUCINATION DETECTED:")
        for m in hall["mismatches"]:
            print(f"     - {m}")

    # ---- proof-point scorecard ----
    proofs = {
        "1_opus_subprocess_merge_real": all(
            r and r.get("joint_topic") for r in frozen_records)
            and all((LOGS_DIR / f"merge_{c['cand_id']}.json").exists()
                    for c in inputs["candidates"]),
        "2_report_injection_ground_truth": (LOGS_DIR / "report_log.md").exists()
            and "[REPORT]" in (LOGS_DIR / "report_log.md").read_text(),
        "3_four_gate_deterministic": determinism_ok,
        "4_no_hallucination": hall["no_hallucination"],
    }
    print("\n" + "=" * 70)
    print("PROOF-POINT SCORECARD")
    print("=" * 70)
    for name, ok in proofs.items():
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}")
    (RUN_DIR / "proof_scorecard.json").write_text(json.dumps(
        {"proofs": proofs, "all_pass": all(proofs.values()),
         "generated_at": datetime.now(timezone.utc).isoformat()}, indent=2))

    all_pass = all(proofs.values())
    print("\n" + ("ALL FOUR PROOF POINTS PASS." if all_pass
                  else "ONE OR MORE PROOF POINTS FAILED."))
    return 0 if all_pass else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
